### ISSUE TITLE
Nit: Looks like a typo - Did you mean 'tweet' instead of 'movie'

### ISSUE THREAD

**Issue by vbiyer** [mayaepps/SimpleTwitter#2]
https://github.com/mayaepps/SimpleTwitter/blob/25b0c74f832c36cec6b1002fe23a41869deab644/app/src/main/java/com/codepath/apps/restclienttemplate/TimelineActivity.java#L71

**Comment by mayaepps** [comment]
Fixed, thanks!  I think I was looking at Flixster for reference and got mixed up!
